[package]
name = "wasabi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.24.1"
tract-onnx = "0.16.5"
wasm-bindgen = "0.2.80"  # for web
console_error_panic_hook = "0.1.7"  # for web

[[bin]]
name = "detect"
path = "src/bin/detect.rs"
