version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
      - ./app/tmp:/tmp
    ports:
      - 8000:8000
    expose:
      - 8000

  envoy:
    image: envoyproxy/envoy:v1.17-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-unknown-unknown/release/proxy_wasm.wasm:/etc/envoy/proxy_wasm.wasm
    ports:
      - 10000:10000
      - 10001:10001
    links:
      - app
